# Action Name
name: Main Automated Builds

# Controls when the action will run
on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"
  pull_request:

# Workflow Jobs
jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1 - Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2 - Extract Environment Variables
      - name: Extract Environment Variables
        uses: FranzDiebold/github-env-vars-action@v2

      # Step 3 - Setup NodeJS
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Step 4 - Install NPM Packages
      - name: Install NPM Packages
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Step 5 - Build the Module
      - name: Build Module
        run: npm run build
      
      # Step 6 - Test the Module
      - name: Test Module
        run: npm run test

      # Step 7 - Extract Package Version
      - name: Extract Package Version
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: packageVersion
        uses: Saionaro/extract-package-version@v1.3.0

      # Step 8 - Check Package Version
      - name: Check Package Version
        if: ${{ startsWith(github.ref, 'refs/tags/') && steps.packageVersion.outputs.version != env.CI_REF_NAME }}
        run: exit 1

      # Step 9 - Publish to NPM
      - name: Publish to NPM
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Step 10 - Generate the Changelog
      - name: Generate the Changelog
        id: changelog
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: metcalfc/changelog-generator@v4.3.1
        with:
          mytoken: ${{ secrets.GITHUB_TOKEN }}

      # Step 11 - Create GitHub Release
      - name: Create GitHub Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: ncipollo/release-action@v1
        with:
          name: Version ${{ env.CI_REF_NAME }}
          body: ${{ steps.changelog.outputs.changelog }}
          tag: ${{ env.CI_REF_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
